services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     -  "8000:8000"
    volumes:
     - .:/app
    restart: always
    command: python app/manage.py runserver 0.0.0.0:8000

#  ipfs:
#    image: ipfs/go-ipfs
#    container_name: ipfs
    #    ports:
    #  - "4001:4001"
    #  - "5001:5001"
    #  - "8080:8080"
    # volumes:
    #  - ./data/ipfs:/data/ipfs
    #restart: always

  # ganache:
    #image: trufflesuite/ganache:lastest
    #container_name: ganache
    #ports:
    #  - "7545:7545"
