services:
  django: &django
    build:
      context: .
      dockerfile: compose/Dockerfile
    depends_on:
      - redis
    ports:
     -  "8000:8000"
    volumes:
     - .:/app
    env_file:
      - .env
    restart: always
    command: /start

  redis:
    image: redis:latest
    container_name: redis

  celeryworker:
    <<: *django
    image: etherium_local_celeryworker
    container_name: etherium_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: etherium_local_celerybeat
    container_name: etherium_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: etherium_local_flower
    container_name: etherium_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
#  ipfs:
#    image: ipfs/go-ipfs
#    container_name: ipfs
    #    ports:
    #  - "4001:4001"
    #  - "5001:5001"
    #  - "8080:8080"
    # volumes:
    #  - ./data/ipfs:/data/ipfs
    #restart: always

  # ganache:
    #image: trufflesuite/ganache:lastest
    #container_name: ganache
    #ports:
    #  - "7545:7545"
