# Generated by Django 5.1.2 on 2024-10-16 13:40

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=256)),
                ("description", tinymce.models.HTMLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
