# Generated by Django 5.1.2 on 2024-10-16 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="image",
        ),
        migrations.AddField(
            model_name="flat",
            name="is_purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FlatImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "flat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="flat.flat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
