# Generated by Django 5.1.2 on 2024-10-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_remove_flat_image_flat_is_purchased_flatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
